### ISSUE TITLE
Password change validation in my-area not working correctly

### ISSUE THREAD

**Issue by martijnjanssen** [AreaFiftyLAN/lancie-frontend#321]
The password validation lets you change the password to something else and does not give any feedback to the user whatsoever. It just assumes the password is changed correctly and closes the form.

**Comment by MatthijsKok** [comment]
Fixed in #356.

**Comment by martijnjanssen** [comment]
This issue is not resolved, this is in my-area. The PR that is closed did not change anything in there.
